### ISSUE TITLE
New projects should use npm instead of github for revelry-components

### ISSUE THREAD

**Issue by grossvogel** [revelrylabs/slush-revelry#7]
The [package.json used in new projects](https://github.com/revelrylabs/slush-revelry/blob/master/templates/new/package.json) should pull the component library (`revelry-components`) from npm instead of github. The current version at this time is 2.0.2, but version 3 is expected to be published soon, so check out the [npm package details](https://www.npmjs.com/package/revelry-components).

**Comment by prehnRA** [comment]
Done and merged!
